copyright: Copyright &copy; 2021 - 2023 <a href="https://github.com/howie6879/weekly">howie.hu</a>.
extra:
  social:
  - icon: fontawesome/brands/telegram
    link: https://t.me/howie_weekly
  - icon: fontawesome/brands/weixin
    link: https://images-1252557999.file.myqcloud.com/uPic/ETIbMe.jpg
  - icon: fontawesome/solid/blog
    link: https://www.howie6879.com
  - icon: fontawesome/brands/github-alt
    link: https://github.com/howie6879
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/howie6879
  - icon: fontawesome/solid/rss
    link: https://weekly.howie6879.com/rss/rss.xml
extra_css:
- statics/css/ui.css
- statics/css/custom.css
- https://gw.alipayobjects.com/os/k/font/lxgwwenkaiscreenr.css
extra_javascript:
- statics/js/custom.js
markdown_extensions:
- smarty
- toc:
    permalink: []
- admonition
- def_list
- codehilite
nav:
- 🌈 创刊寄语:
  - 首页: ./index.md
- 🐍 2026 读书年:
  - 06-21~06-27.读书周: ./2026/06-21~06-27.读书周.md
- 🍀 今日推荐:
  - 🍀 今日推荐: ./recommend/index.md
- 💻 软件推荐:
  - 🍏 我的 macOS 常用软件: ./soft/mac.md
  - 🤖 ChatGPT 开源应用月度排名: ./soft/chatgpt.md
- 👏 GPT Plus: https://gpt5plus.com/?ref=howie6879_weekly
- 🔗 RSS订阅: ./rss/rss.xml
plugins:
- search:
    separator: '[\s\u200b\-]'
- open-in-new-tab
- git-revision-date-localized
repo_name: howie6879/weekly
repo_url: https://github.com/howie6879/weekly
site_author: howie.hu
site_description: 老胡的信息周刊，为您带来各种值得收藏的软件项目以及资料网站 >>> 奇文共欣赏，疑义相与析
site_name: 鼠头鸭脖周刊
site_url: https://wiki.zhihu.blog/
theme:
  custom_dir: overrides
  favicon: ./statics/images/favicon.ico
  features:
  - content.code.annotate
  - navigation.expand
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  font:
    code: Roboto Mono
    text: Roboto
  language: zh
  logo: ./statics/images/howie.jpeg
  name: material
  palette:
  - accent: indigo
    primary: blue
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  search_index_only: true
use_directory_urls: false
